theme = "solarized-dark"
icons = "awesome"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "enp5s0"
interval = 5

[[block]]
block = "load"
interval = 5
format = "{1m} {5m}"

[[block]]
block = "cpu"
interval = 5

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "time"
interval = 5
format = "%a %d/%m %R"
