[theme]
name = "solarized-dark"

[icons]
name = "awesome"

[[block]]
block = "music"
player = "mopidy"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "load"
interval = 5
format = "{1m} {5m}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{Mup}%"
format_swap = "{SUp}%"

[[block]]
block = "time"
interval = 5
format = "%m.%d %R"

[[block]]
block = "custom"
command = "mouse-battery-read"
interval = 100

